### ISSUE TITLE
How to build the engine on linux ?

### ISSUE THREAD

**Issue by DraGiuS** [gecko0307/dagon#26]
Hi, i would like to know how to build the engine ?

**Comment by gecko0307** [comment]
Dagon is a source library, so there's little benefit from compiling it alone (although it's possible). You may want to build an application instead. There's a [Dagom demo app](https://github.com/gecko0307/dagon-demo) which shows all main features of the engine. You can build it using [dub](https://github.com/dlang/dub), just run `dub build`. Be sure to install [Digital Mars D compiler (dmd)](http://dlang.org) first. There're official packages for Ubuntu/Debian, Fedora and openSUSE.
