### ISSUE TITLE
entity rotation causes disposition of scale.

### ISSUE THREAD

**Issue by aferust** [gecko0307/dagon#45]
I want my plane to do a barrel roll. it does with following code. However, disruptions in scale also occurs.  Is it a bug or, am I on a totally wrong way?

```
auto q = rotationQuaternion(Axis.z, degtorad(stepAngle * dt)); // stepAngle = 150.0f;
plane.rotation.z += q.z;
```

**Comment by gecko0307** [comment]
It seems it's a bug (scaling applied after rotation), I'll fix this as soon as possible.

**Comment by aferust** [comment]
Yes, it needs some helper methods like: http://wiki.ogre3d.org/Euler+Angle+Class

I think camera has something like that already: /graphics/tbcamera.d
