### ISSUE TITLE
Loading texture images from embedded sources such as base64 string or/and raw data pointer with dimensions

### ISSUE THREAD

**Issue by aferust** [gecko0307/dagon#48]
Benefits:
-This would allow developer to manipulate textures dynamically using image processing libraries such as opencv, dcv.
- Distribution friendly.

This can be done with some function like addTextureAssetFromBase64.

**Comment by aferust** [comment]
I have realized that dlib has image io functionality already. So, it must be easy to implement.

**Comment by Timu5** [comment]
You can already construct a texture from dlib Image, so just construct one, fill pixels with setPixel and pass Image object to texture constructor.
