### ISSUE TITLE
Major redesign

### ISSUE THREAD

**Issue by gecko0307** [gecko0307/dagon#54]
In upcoming Dagon 0.11, which will be a step towards 1.0, I'm rethinking some architectural concepts and parts of the API. This work is done in [dagon-ng](https://github.com/gecko0307/dagon/tree/dagon-ng) branch. Main points are the following:

* Less coupling in module structure. Currently it's a total mess with modules from different packages randomly depending on each other. New structure will have strict layout with modules only depending on lower-level packages:

![dagon-new-package-layout](https://user-images.githubusercontent.com/1396859/58368056-1620a600-7ef0-11e9-98ac-5dc0a4924e26.jpg)

* Renderer reimplementation. It should be possible to easily switch different renderers and output modes (for example, to visualize gbuffer). In current Dagon it is nearly impossible for the user to implement his own renderer without rewriting much of the engine. My idea is to break up the renderer to [pipelines](https://github.com/gecko0307/dagon/blob/dagon-ng/src/dagon/render/pipeline.d) and [stages](https://github.com/gecko0307/dagon/blob/dagon-ng/src/dagon/render/stage.d) which will allow easy extending and reuse of built-in rendering functionality. Also deferred renderer will be improved and optimized.
* Reduce shader switches to improve performance. Use entity groups whenever possible.
* Post-processing filters will also be ported to stages.
* Nuklear integration and Freetype fonts support will be moved to subpackages (`dagon:nuklear` and `dagon:ftfont`). Subconfigurations are cumbersome and not very intuitive, so all functionality that depends on additional external libraries should be plugged in explicitly. Core Dagon will depend only on SDL. 
* Use official [bindbc-freetype](https://github.com/BindBC/bindbc-freetype) instead of custom binding.
* Use latest versions of other bindings.

This will be a breaking change. See [editor.d](https://github.com/gecko0307/dagon-editor/blob/master/src/editor.d) for an example of new user-side code.

Status:
* [x] Window creation, event system
* [x] Scene menegement
* [x] Asset management
* [x] Deferred renderer
* [x] Forward renderer for transparent objects
* [x] Entities
* [x] Tweens
* [x] Built-in shapes
* [x] *.obj
* [x] *.iqm (will be implemented as extension)
* [x] *.asset
* [x] Animated models (will be implemented as extension)
* [x] Images
* [x] Textures
* [x] Materials, shaders
* [x] Environment maps
* [x] Sun lights
* [x] Area lights
* [x] Shadows
* [x] Terrain
* [x] Sky
* [x] Water
* [x] Particles
* [x] Decals
* [x] Post-processing
* [x] Text rendering
* [x] Nuklear GUI
* [x] Freeview controller
* [x] First person controller

**Comment by leotada** [comment]
Is there a way to use a rendering engine like this?
May be useful.
http://diligentgraphics.com/diligent-engine/

**Comment by gecko0307** [comment]
I'm not a fan of using third-party renderer, here's why:
- Additional layer of complexity and obscurity. Pure OpenGL has strictly defined behaviour, it is well documented and supported, while an abstraction layer must have its own bugs and quirks to cope with.
- OpenGL is high level enough. Maybe Vulkan or Metal require an additional abstraction layer for convenience and productivity, but OpenGL doesn't. There's little benefit of using an abstract API other than supporting several APIs.
- Does macOS support matter that much? It's the only desktop platform that doesn't have decent OpenGL these days. That sucks of course, but that alone is not such a big thumb down for OpenGL. I've written an [article](https://github.com/gecko0307/dlib/wiki/Why-doesn't-dlib-support-macOS) on this topic for those who care.
- Non-D dependencies can be hard to install on Linux (I already receive complaints about Nuklear). On Windows we can ship all the DLLs with the application, which is very convenient for the user. On Linux we can't do that beacuse shared libraries normally should be installed using the package manager or compiled from source.
