### ISSUE TITLE
Nuklear library not found

### ISSUE THREAD

**Issue by DeenOConnor** [gecko0307/dagon#57]
I tried to compile dagon-demo, tutorial 1 and dagon-shooter and there always was the same problem:
[deen@parrot] : [~/Programs/dagon-demo-master]
[$]> ./dagondemo
Error: Nuklear library is not found. Please, install Nuklear.

Even with sudo:
[deen@parrot] : [~/Programs/dagon-demo-master]
[$]> sudo !!
sudo ./dagondemo
[sudo] пароль для deen: 
Error: Nuklear library is not found. Please, install Nuklear.

Even though dub downloads nuklear and builds it, all the projects i tried tell me that i need to install nuklear.

I cloned nuklear, went into c folder and ran cmake . :
![image](https://user-images.githubusercontent.com/50165686/63518168-1fbea780-c4f9-11e9-9e7a-56a90310cb0d.png)

After that i tried make && make install:
![image](https://user-images.githubusercontent.com/50165686/63518233-44b31a80-c4f9-11e9-96e6-aa00a496826a.png)

And tried running the demo again:
[deen@parrot] : [~/Programs/bindbc-nuklear/c]
[$]> cd ../../dagon-demo-master/
[deen@parrot] : [~/Programs/dagon-demo-master]
[$]> ./dagondemo 
Error: Nuklear library is not found. Please, install Nuklear.

What should i do to install nuklear?
Linux parrot 5.2.0-2parrot1-amd64 #1 SMP Parrot 5.2.7-2parrot1 (2019-08-12) x86_64 GNU/Linux

**Comment by Timu5** [comment]
That's bindbc-nuklear problem, "make install" will only copy nuklear to "./bindbc-nuklear/lib/" directory, but in order to work property libnuklear.so and libnuklear.so.4.1.0 should be placed in "/usr/local/lib/". You can try to copy both this files manually.

**Comment by DeenOConnor** [comment]
Copied libnuklear.so.4.1.0 to /usr/local/lib/nuklear and created a symlink libnuklear.so next to it, that didn't work.
Copied those directly into /usr/local/lib, didn't work too.

**Comment by Timu5** [comment]
Sorry, my bad, symbolic link should be named "nuklear.so" without "lib" prefix so full path is "/usr/local/lib/nuklear.so".

**Comment by DeenOConnor** [comment]
It worked, thanks a lot.
