### ISSUE TITLE
Optimize Forward renderer

### ISSUE THREAD

**Issue by RUSshy** [gecko0307/dagon#61]
I noticed each entity binds its shader each draw call, instead of grouping them and only bind shader once, transparent entities needs to be sorted from front to back i think

That will help with performance when rendering lot of entities

- https://github.com/gecko0307/dagon/blob/d8e88d1d405e4c578728f328c8bd84677413d31b/src/dagon/render/deferred/forwardstage.d

- [ ] Sort calls by shaders, and only bind the shader once per group
- [ ] Sort entities based on camera distance

**Comment by RUSshy** [comment]
Oh i just noticed it is already tracker here: https://github.com/gecko0307/dagon/issues/54

**Comment by gecko0307** [comment]
Yep, I'm still working on forward renderer, and sorting will be supported.
