### ISSUE TITLE
stb fails to link under linux

### ISSUE THREAD

**Issue by creutzerb** [gecko0307/dagon#70]
Hello,

I get the the problem mentioned here https://github.com/Temtaime/stb/issues/3#issue-950050179  whether it's local or not.

Any idea where that might be coming from ? 
Thanks.

**Comment by gecko0307** [comment]
Seems that `compress_for_stb_image_write` ends up missing from the binary at link stage.
I've added a `static this` that makes a reference to this function so that it is not removed. A bit hacky solution, but should work.
