### ISSUE TITLE
Crash when loading obj file with quads

### ISSUE THREAD

**Issue by JakeCoxon** [gecko0307/dagon#73]
Obj file has 
```f 1/1/1 2/2/1 4/3/1 3/4/1```

I think this line needs to be else if 

```
  }
  if (sscanf(tmpStr.ptr, "f %u/%u/%u %u/%u/%u %u/%u/%u", &v1, &t1, &n1, &v2, &t2, &n2, &v3, &t3, &n3) == 9)
  {
```

**Comment by gecko0307** [comment]
By the way, quads can be properly processed at this point, I'll do it soon.

**Comment by JakeCoxon** [comment]
Thanks! I worked around it by exporting tris but I thought I'd mention it anyway
