### ISSUE TITLE
Getting Started steps fails with linking errors on __stdio_common_vfprintf, __chkstk, and __stdio_common_vswprintf

### ISSUE THREAD

**Issue by EricPoggel** [gecko0307/dagon#74]
I'm running Windows 10 64 bit, with `DMD32 D Compiler v2.098.1-dirty`  I tried it for the first time today, and dagon/dlib had never previously been installed via dub.  Then I repeated the same steps a second time in a clean folder so I could capture the error output:

```batch
C:\home\projects\game3>dub init --type=dagon
Performing "debug" build using C:\dev\dmd\dmd2\windows\bin\dmd.exe for x86_64.
dagon:init-exec 0.12.1: building configuration "application"...
Linking...
Running ../../../Users/user/AppData/Local/dub/packages/dagon-0.12.1/dagon/init-exec/dagon_init-exec.exe
Successfully created an empty project in 'C:\home\projects\game3'.
Package successfully created in .

C:\home\projects\game3>dub build
Performing "debug" build using C:\dev\dmd\dmd2\windows\bin\dmd.exe for x86_64.
dlib 0.23.0: target for configuration "library" is up to date.
dagon 0.12.1: target for configuration "library" is up to date.
game3 ~master: building configuration "application"...
Linking...
lld-link: error: undefined symbol: __stdio_common_vfprintf
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stb_)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stb_append_to_file)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(fprintf)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(vfprintf)

lld-link: error: undefined symbol: __chkstk
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stb_replacedir)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stb_replaceext)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stb_fopen)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stb_fclose)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(readdir_raw)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stbi_load_gif_from_memory)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stbi_zlib_decode_malloc_guesssize)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stbi_zlib_decode_malloc)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stbi_zlib_decode_malloc_guesssize_headerflag)
>>> referenced by stb_x64.lib(main-cd4e4a.o):(stbi_zlib_decode_buffer)
>>> referenced 4 more times

lld-link: error: undefined symbol: __stdio_common_vswprintf
>>> referenced by stb_x64.lib(main-cd4e4a.o):(_swprintf)
Error: linker exited with status 1
C:\dev\dmd\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

**Comment by gecko0307** [comment]
I've tested with 2.098.1 (both with LLD and MS linker), can't reproduce. Did you try installing Visual Studio? DMD should use it for linking, when possible.

**Comment by EricPoggel** [comment]
Unfortunately that didn't fix the issue. 

1. I uninstalled DMD 2.098.1 and reinstalled it with the default options, other than installing it to a custom path where I keep my dev tools.  
2. I installed Visual Studio 2019 also as part of the dmd installation process.  I didn't change that from the default.
3. I deleted all files/folders in the appdata/local/dub/packages folder.
4. In a new empty directory I ran `dub init --type=dagon` and `dub build`.

Then I get the same error I pasted above.

I previously didn't have visual studio or any of the visual studio build tools installed.  I'm not sure how to tell dub or dmd which linker to use.

**Comment by EricPoggel** [comment]
Today I tried it on a second computer.  I installed DMD using all the default options, plus also installing DMC and VisualD just in case.  The steps above gave me the same linking error.

Is it possible you may have something else installed on your Windows pc that satisfies the missing dependency on my own computers, or something configured differently than the default?

**Comment by gecko0307** [comment]
I'm not sure, maybe stb_x64.lib is compiled with some unusual settings. I'll test on another windows machine.

**Comment by EricPoggel** [comment]
This resolved the linking issues.  Thank you!
