### ISSUE TITLE
Install Nuklear is meaningless

### ISSUE THREAD

**Issue by paulfurber** [gecko0307/dagon#81]
Hi there,

Nuklear is a header-only library written in C. It's not a shared library nor are there any ways of making it one from its repo. Is there perhaps a repo that I can install it from please?

**Comment by gecko0307** [comment]
Nuklear is loaded dynamically using BindBC loader. Dagon uses [bindbc-nuklear](https://github.com/gecko0307/dagon/tree/master/extensions/nuklear/thirdparty/bindbc-nuklear-0.4.3) dynamic binding, it includes a [CMake configuration](https://github.com/gecko0307/dagon/tree/master/extensions/nuklear/thirdparty/bindbc-nuklear-0.4.3/c) to compile as a shared library.

**Comment by gecko0307** [comment]
I've added an [instruction](https://github.com/gecko0307/dagon#runtime-dependencies) on building Nuklear with CMake. Also I've fixed its configuration so that the library can be installed with `make install` as usual.
