### ISSUE TITLE
Default program fails to run on Fedora 39

### ISSUE THREAD

**Issue by mxruben** [gecko0307/dagon#93]
When I init a new project with ```dub init --type=dagon```, it builds fine, but gives me multiple runtime errors when run:
```
libdecor-gtk-WARNING: Failed to initialize GTK
Failed to load plugin 'libdecor-gtk.so': failed to init
Error: Dagon requires OpenGL 4.0, but it seems that your graphics card does not support it
Error Program exited with code 1
```
I have gtk4, libdecor and SDL2 development libraries installed, so I'm not sure where the gtk errors are coming from. My graphics card (Intel Iris Xe) most definitely supports OpenGL 4. Maybe that error is just a side-effect of the first one.

Relevant library versions:
Dagon: 0.16.0
SDL: 2.28.5-1
libdecor: 0.2.2-1
gtk: 4.12.5-1

Thanks for your help!

**Comment by mxruben** [comment]
I looks like this is an issue with my SDL installation. I tried using bindbc-sdl in a new project and I got the same libdecor errors. I also gave it a shot with just c++ and the same problems happened. Safe to say it is not a problem with this lib. Oddly everything runs fine when run as root. Probably an issue with my system.

**Comment by mxruben** [comment]
Update, it turns out that it was a wayland issue. When run with SDL_VIDEODRIVER=x11, the first few errors are gone. Apparently, wayland requires a full event loop for a window to be displayed. See [this](https://github.com/libsdl-org/SDL/issues/6074) issue for more info.

Dagon still thinks my graphics card is ancient or non-existent because I still get this error: ```Error: Dagon requires OpenGL 4.0, but it seems that your graphics card does not support it``` unless run as root. Going to reopen because of this.

**Comment by mxruben** [comment]
Ok, things are really getting weird, I found out that when I run dub through vs-code's integrated terminal (with ```SDL_VIDEODRIVER=x11```), everything just works fine, but for some reason when I run it with gnome-console, I get the OpenGL error. To make things even weirder, when I use gnome-terminal, everything also works as expected. When I use normal bindbc-opengl with bindbc-sdl, it detects opengl no matter what terminal app I use. I am mega confused right now.

**Comment by gecko0307** [comment]
Seems that wayland support was missing in bindbc-opengl 1.0. I've updated dependencies, so now the context should initialize correctly.

**Comment by mxruben** [comment]
Thanks! It works great now on both x11 and wayland.
